name: Inference Pipeline

on:
  workflow_dispatch:

jobs:
  infer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r streamlit_app/requirements.txt
          pip install "hopsworks[python]"  # ✅ This installs confluent-kafka

      - name: Run Inference
        run: |
          python scripts/inference.py
          python scripts/upload_predictions_to_hopsworks.py
